# Generated by Django 4.2.26 on 2025-12-01 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Milk & Curd', 'Milk & Curd'), ('Ice Creams', 'Ice Creams'), ('Daily Groceries', 'Daily Groceries'), ('Electrical Items', 'Electrical Items'), ('Home Utility Items', 'Home Utility Items'), ('Soaps & Detergents', 'Soaps & Detergents'), ('Snacks & Biscuits', 'Snacks & Biscuits'), ('Cool Drinks', 'Cool Drinks'), ('Personal Care', 'Personal Care'), ('Agricultural Items', 'Agricultural Items')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='products/')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
